name: ashley_dart
description: A port of libgdx Ashley to dart
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  

dev_dependencies:
  test: ^1.22.2
  mockito: ^5.3.2
  lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

